server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monitor_production?useUnicode=true&characterEncoding=utf-8
    username: root
    password: sfiroot
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

shiro:



